CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  inviteCode VARCHAR(50) NOT NULL UNIQUE,
  adminId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  teamId INT NULL,
  role ENUM('ADMIN', 'MEMBER') NOT NULL DEFAULT 'MEMBER',
  status ENUM('PENDING', 'APPROVED') NOT NULL DEFAULT 'APPROVED',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_team FOREIGN KEY (teamId) REFERENCES teams(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tasks_schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NULL,
  teamId INT NULL,
  type ENUM('PERSONAL', 'TEAM') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  dpName VARCHAR(100) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Wait',
  targetDate DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_tasks_team FOREIGN KEY (teamId) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
  id INT AUTO_INCREMENT PRIMARY KEY,
  requesterId INT NOT NULL,
  addresseeId INT NOT NULL,
  status ENUM('PENDING', 'ACCEPTED') NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acceptedAt DATETIME NULL,
  CONSTRAINT fk_friends_requester FOREIGN KEY (requesterId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friends_addressee FOREIGN KEY (addresseeId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_friend_self CHECK (requesterId <> addresseeId),
  UNIQUE KEY uq_friend_pair (requesterId, addresseeId)
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  authorId INT NOT NULL,
  targetUserId INT NOT NULL,
  teamId INT NULL,
  type ENUM('PERSONAL', 'TEAM') NOT NULL,
  content TEXT NOT NULL,
  score INT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_author FOREIGN KEY (authorId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_target FOREIGN KEY (targetUserId) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_team FOREIGN KEY (teamId) REFERENCES teams(id) ON DELETE SET NULL
);
