const { execute } = require('../config/db.config');

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chats (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          senderId NUMBER NOT NULL,
          receiverId NUMBER NOT NULL,
          message VARCHAR2(2000 CHAR) NOT NULL,
          timestamp DATE DEFAULT SYSDATE NOT NULL
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const create = async ({ senderId, receiverId, message }) => {
  const sql = `INSERT INTO chats (senderId, receiverId, message, timestamp) VALUES (:senderId, :receiverId, :message, SYSDATE)`;
  await execute(sql, { senderId, receiverId, message });
  const result = await execute(
    `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId", message AS "message", timestamp AS "timestamp"
     FROM chats
     WHERE senderId = :senderId AND receiverId = :receiverId
     ORDER BY timestamp DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { senderId, receiverId }
  );
  return result.rows[0] || { senderId, receiverId, message, timestamp: new Date() };
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const binds = {};
  const clauses = [];
  keys.forEach((key) => {
    if (key === 'or') return;
    clauses.push(`${key} = :${key}`);
    binds[key] = filter[key];
  });

  let sql = `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId", message AS "message", timestamp AS "timestamp" FROM chats`;
  if (filter.or) {
    const orClauses = filter.or.map((cond, index) => {
      const keys = Object.keys(cond);
      return keys.map((key) => {
        binds[`or_${index}_${key}`] = cond[key];
        return `${key} = :or_${index}_${key}`;
      }).join(' AND ');
    });
    sql += ` WHERE (${orClauses.join(' OR ')})`;
  } else if (clauses.length) {
    sql += ` WHERE ${clauses.join(' AND ')}`;
  }
  sql += ' ORDER BY timestamp';

  const result = await execute(sql, binds);
  return result.rows;
};

const search = async (userId, query) => {
  const sql = `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId", message AS "message", timestamp AS "timestamp"
               FROM chats WHERE (senderId = :userId OR receiverId = :userId) AND LOWER(message) LIKE LOWER(:query) ORDER BY timestamp`;
  const result = await execute(sql, { userId, query: `%${query}%` });
  return result.rows;
};

const getConversationSummaries = async (userId) => {
  const sql = `
    SELECT
      u.id AS "userId",
      u.userid AS "userid",
      u.email AS "email",
      u.name AS "name",
      u.profile AS "profile",
      u.presenceStatus AS "presenceStatus",
      latest.message AS "lastMessage",
      latest.timestamp AS "lastTimestamp"
    FROM (
      SELECT otherId, message, timestamp
      FROM (
        SELECT
          CASE WHEN senderId = :userId THEN receiverId ELSE senderId END AS otherId,
          message,
          timestamp,
          ROW_NUMBER() OVER (
            PARTITION BY CASE WHEN senderId = :userId THEN receiverId ELSE senderId END
            ORDER BY timestamp DESC, id DESC
          ) AS rn
        FROM chats
        WHERE senderId = :userId OR receiverId = :userId
      )
      WHERE rn = 1
    ) latest
    JOIN users u ON u.id = latest.otherId
    ORDER BY latest.timestamp DESC
  `;
  const result = await execute(sql, { userId });
  return result.rows;
};

module.exports = { ensureTable, create, find, search, getConversationSummaries };
