const { execute } = require('../config/db.config');

const runIgnore = async (sql, ignoredCodes = []) => {
  try {
    await execute(sql);
  } catch (error) {
    if (!ignoredCodes.includes(error.errorNum)) throw error;
  }
};

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chats (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          senderId NUMBER NOT NULL,
          receiverId NUMBER NOT NULL,
          message VARCHAR2(2000 CHAR) NOT NULL,
          timestamp DATE DEFAULT SYSDATE NOT NULL
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await runIgnore(`ALTER TABLE chats ADD deletedAt DATE`, [1430]);

  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chat_groups (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR2(100 CHAR) NOT NULL,
          ownerId NUMBER NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chat_group_members (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          groupId NUMBER NOT NULL,
          userId NUMBER NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL,
          CONSTRAINT uq_chat_group_member UNIQUE (groupId, userId)
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chat_group_messages (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          groupId NUMBER NOT NULL,
          senderId NUMBER NOT NULL,
          message VARCHAR2(2000 CHAR) NOT NULL,
          timestamp DATE DEFAULT SYSDATE NOT NULL,
          deletedAt DATE
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE chat_reads (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          userId NUMBER NOT NULL,
          targetType VARCHAR2(20 CHAR) NOT NULL,
          targetId NUMBER NOT NULL,
          lastReadAt DATE DEFAULT SYSDATE NOT NULL,
          CONSTRAINT uq_chat_read UNIQUE (userId, targetType, targetId)
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const create = async ({ senderId, receiverId, message }) => {
  await execute(
    `INSERT INTO chats (senderId, receiverId, message, timestamp) VALUES (:senderId, :receiverId, :message, SYSDATE)`,
    { senderId, receiverId, message }
  );
  const result = await execute(
    `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId", message AS "message",
            timestamp AS "timestamp", deletedAt AS "deletedAt"
     FROM chats
     WHERE senderId = :senderId AND receiverId = :receiverId
     ORDER BY timestamp DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { senderId, receiverId }
  );
  return result.rows[0] || null;
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const binds = {};
  const clauses = [];
  keys.forEach((key) => {
    if (key === 'or') return;
    clauses.push(`${key} = :${key}`);
    binds[key] = filter[key];
  });

  let sql = `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId",
                    CASE WHEN deletedAt IS NULL THEN message ELSE '삭제된 메시지입니다.' END AS "message",
                    timestamp AS "timestamp", deletedAt AS "deletedAt"
             FROM chats`;
  if (filter.or) {
    const orClauses = filter.or.map((cond, index) => Object.keys(cond).map((key) => {
      binds[`or_${index}_${key}`] = cond[key];
      return `${key} = :or_${index}_${key}`;
    }).join(' AND '));
    sql += ` WHERE (${orClauses.join(' OR ')})`;
  } else if (clauses.length) {
    sql += ` WHERE ${clauses.join(' AND ')}`;
  }
  sql += ' ORDER BY timestamp, id';

  const result = await execute(sql, binds);
  return result.rows;
};

const search = async (userId, query) => {
  const sql = `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId", message AS "message",
                      timestamp AS "timestamp", deletedAt AS "deletedAt"
               FROM chats
               WHERE deletedAt IS NULL
                 AND (senderId = :userId OR receiverId = :userId)
                 AND LOWER(message) LIKE LOWER(:query)
               ORDER BY timestamp`;
  const result = await execute(sql, { userId, query: `%${query}%` });
  return result.rows;
};

const deleteMessage = async ({ messageId, userId }) => {
  await execute(`UPDATE chats SET deletedAt = SYSDATE WHERE id = :messageId AND senderId = :userId`, { messageId, userId });
  const result = await execute(
    `SELECT id AS "id", senderId AS "senderId", receiverId AS "receiverId",
            CASE WHEN deletedAt IS NULL THEN message ELSE '삭제된 메시지입니다.' END AS "message",
            timestamp AS "timestamp", deletedAt AS "deletedAt"
     FROM chats WHERE id = :messageId`,
    { messageId }
  );
  return result.rows[0] || null;
};

const upsertRead = async ({ userId, targetType, targetId }) => {
  await execute(`
    MERGE INTO chat_reads r
    USING (SELECT :userId AS userId, :targetType AS targetType, :targetId AS targetId FROM dual) src
    ON (r.userId = src.userId AND r.targetType = src.targetType AND r.targetId = src.targetId)
    WHEN MATCHED THEN UPDATE SET r.lastReadAt = SYSDATE
    WHEN NOT MATCHED THEN INSERT (userId, targetType, targetId, lastReadAt)
      VALUES (:userId, :targetType, :targetId, SYSDATE)
  `, { userId, targetType, targetId });
};

const createGroup = async ({ ownerId, name, memberIds }) => {
  await execute(`INSERT INTO chat_groups (name, ownerId, createdAt) VALUES (:name, :ownerId, SYSDATE)`, { name, ownerId });
  const created = await execute(
    `SELECT id AS "id", name AS "name", ownerId AS "ownerId", createdAt AS "createdAt"
     FROM chat_groups
     WHERE ownerId = :ownerId
     ORDER BY createdAt DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { ownerId }
  );
  const group = created.rows[0];
  const uniqueMembers = [...new Set([ownerId, ...memberIds.map(Number).filter(Boolean)])];
  await Promise.all(uniqueMembers.map((userId) => addGroupMember({ groupId: group.id, userId })));
  return group;
};

const addGroupMember = async ({ groupId, userId }) => {
  await execute(`
    BEGIN
      INSERT INTO chat_group_members (groupId, userId, createdAt) VALUES (:groupId, :userId, SYSDATE);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;
  `, { groupId, userId });
};

const isGroupMember = async ({ groupId, userId }) => {
  const result = await execute(
    `SELECT id AS "id" FROM chat_group_members WHERE groupId = :groupId AND userId = :userId`,
    { groupId, userId }
  );
  return Boolean(result.rows[0]);
};

const getGroupMemberIds = async (groupId) => {
  const result = await execute(
    `SELECT userId AS "userId" FROM chat_group_members WHERE groupId = :groupId`,
    { groupId }
  );
  return result.rows.map((row) => row.userId);
};

const createGroupMessage = async ({ groupId, senderId, message }) => {
  await execute(
    `INSERT INTO chat_group_messages (groupId, senderId, message, timestamp) VALUES (:groupId, :senderId, :message, SYSDATE)`,
    { groupId, senderId, message }
  );
  const result = await execute(
    `SELECT gm.id AS "id", gm.groupId AS "groupId", gm.senderId AS "senderId", u.name AS "senderName",
            gm.message AS "message", gm.timestamp AS "timestamp", gm.deletedAt AS "deletedAt"
     FROM chat_group_messages gm
     JOIN users u ON u.id = gm.senderId
     WHERE gm.groupId = :groupId AND gm.senderId = :senderId
     ORDER BY gm.timestamp DESC, gm.id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { groupId, senderId }
  );
  return result.rows[0] || null;
};

const getGroupMessages = async (groupId) => {
  const result = await execute(
    `SELECT gm.id AS "id", gm.groupId AS "groupId", gm.senderId AS "senderId", u.name AS "senderName",
            CASE WHEN gm.deletedAt IS NULL THEN gm.message ELSE '삭제된 메시지입니다.' END AS "message",
            gm.timestamp AS "timestamp", gm.deletedAt AS "deletedAt"
     FROM chat_group_messages gm
     JOIN users u ON u.id = gm.senderId
     WHERE gm.groupId = :groupId
     ORDER BY gm.timestamp, gm.id`,
    { groupId }
  );
  return result.rows;
};

const deleteGroupMessage = async ({ messageId, userId }) => {
  await execute(
    `UPDATE chat_group_messages SET deletedAt = SYSDATE WHERE id = :messageId AND senderId = :userId`,
    { messageId, userId }
  );
  const result = await execute(
    `SELECT id AS "id", groupId AS "groupId", senderId AS "senderId", message AS "message",
            timestamp AS "timestamp", deletedAt AS "deletedAt"
     FROM chat_group_messages WHERE id = :messageId`,
    { messageId }
  );
  return result.rows[0] || null;
};

const getConversationSummaries = async (userId) => {
  const directSql = `
    SELECT
      'direct' AS "type",
      u.id AS "userId",
      u.userid AS "userid",
      u.email AS "email",
      u.name AS "name",
      u.profile AS "profile",
      u.presenceStatus AS "presenceStatus",
      latest.message AS "lastMessage",
      latest.timestamp AS "lastTimestamp",
      (
        SELECT COUNT(*)
        FROM chats c
        LEFT JOIN chat_reads r
          ON r.userId = :userId AND r.targetType = 'direct'
         AND r.targetId = CASE WHEN c.senderId = :userId THEN c.receiverId ELSE c.senderId END
        WHERE c.deletedAt IS NULL
          AND c.receiverId = :userId
          AND c.senderId = u.id
          AND c.timestamp > NVL(r.lastReadAt, TO_DATE('1970-01-01', 'YYYY-MM-DD'))
      ) AS "unreadCount"
    FROM (
      SELECT otherId, message, timestamp
      FROM (
        SELECT
          CASE WHEN senderId = :userId THEN receiverId ELSE senderId END AS otherId,
          CASE WHEN deletedAt IS NULL THEN message ELSE '삭제된 메시지입니다.' END AS message,
          timestamp,
          ROW_NUMBER() OVER (
            PARTITION BY CASE WHEN senderId = :userId THEN receiverId ELSE senderId END
            ORDER BY timestamp DESC, id DESC
          ) AS rn
        FROM chats
        WHERE senderId = :userId OR receiverId = :userId
      )
      WHERE rn = 1
    ) latest
    JOIN users u ON u.id = latest.otherId
    ORDER BY latest.timestamp DESC
  `;

  const groupSql = `
    SELECT
      'group' AS "type",
      g.id AS "groupId",
      g.name AS "name",
      latest.message AS "lastMessage",
      latest.timestamp AS "lastTimestamp",
      (
        SELECT COUNT(*)
        FROM chat_group_messages gm
        LEFT JOIN chat_reads r
          ON r.userId = :userId AND r.targetType = 'group' AND r.targetId = g.id
        WHERE gm.groupId = g.id
          AND gm.senderId != :userId
          AND gm.deletedAt IS NULL
          AND gm.timestamp > NVL(r.lastReadAt, TO_DATE('1970-01-01', 'YYYY-MM-DD'))
      ) AS "unreadCount"
    FROM chat_groups g
    JOIN chat_group_members m ON m.groupId = g.id AND m.userId = :userId
    LEFT JOIN (
      SELECT groupId, CASE WHEN deletedAt IS NULL THEN message ELSE '삭제된 메시지입니다.' END AS message, timestamp
      FROM (
        SELECT groupId, message, timestamp, deletedAt,
               ROW_NUMBER() OVER (PARTITION BY groupId ORDER BY timestamp DESC, id DESC) AS rn
        FROM chat_group_messages
      )
      WHERE rn = 1
    ) latest ON latest.groupId = g.id
    ORDER BY NVL(latest.timestamp, g.createdAt) DESC
  `;

  const [direct, groups] = await Promise.all([
    execute(directSql, { userId }),
    execute(groupSql, { userId })
  ]);
  return { direct: direct.rows, groups: groups.rows };
};

module.exports = {
  ensureTable,
  create,
  find,
  search,
  deleteMessage,
  upsertRead,
  createGroup,
  addGroupMember,
  isGroupMember,
  getGroupMemberIds,
  createGroupMessage,
  getGroupMessages,
  deleteGroupMessage,
  getConversationSummaries
};
