<<<<<<< HEAD
const db = require('../config/db.config');

const Feedback = {
  create: async ({ authorId, targetUserId, teamId, type, content, score }) => {
    const query = `
      INSERT INTO feedbacks (authorId, targetUserId, teamId, type, content, score)
      VALUES (?, ?, ?, ?, ?, ?)
    `;
    const [result] = await db.execute(query, [
      authorId,
      targetUserId,
      teamId,
      type,
      content,
      score
    ]);
    return result;
  },

  findReceivedByUserId: async ({ userId, type }) => {
    const conditions = ['f.targetUserId = ?'];
    const params = [userId];

    if (type) {
      conditions.push('f.type = ?');
      params.push(type);
    }

    const query = `
      SELECT f.id, f.authorId, f.targetUserId, f.teamId, f.type, f.content, f.score, f.createdAt,
             u.name AS authorName, u.email AS authorEmail
      FROM feedbacks f
      JOIN users u ON u.id = f.authorId
      WHERE ${conditions.join(' AND ')}
      ORDER BY f.createdAt DESC
    `;
    const [rows] = await db.execute(query, params);
    return rows;
  },

  findCreatedByUserId: async ({ userId, type }) => {
    const conditions = ['f.authorId = ?'];
    const params = [userId];

    if (type) {
      conditions.push('f.type = ?');
      params.push(type);
    }

    const query = `
      SELECT f.id, f.authorId, f.targetUserId, f.teamId, f.type, f.content, f.score, f.createdAt,
             u.name AS targetName, u.email AS targetEmail
      FROM feedbacks f
      JOIN users u ON u.id = f.targetUserId
      WHERE ${conditions.join(' AND ')}
      ORDER BY f.createdAt DESC
    `;
    const [rows] = await db.execute(query, params);
    return rows;
  },

  deleteByIdAndAuthor: async ({ feedbackId, authorId }) => {
    const query = `
      DELETE FROM feedbacks
      WHERE id = ? AND authorId = ?
    `;
    const [result] = await db.execute(query, [feedbackId, authorId]);
    return result;
  }
};

module.exports = Feedback;
=======
const { execute } = require('../config/db.config');

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE feedbacks (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          fromUserId NUMBER NOT NULL,
          toUserId NUMBER NOT NULL,
          teamId NUMBER NULL,
          content VARCHAR2(1000) NOT NULL,
          rating NUMBER(1) DEFAULT 5 NOT NULL,
          category VARCHAR2(20) DEFAULT ''team'' NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL,
          CONSTRAINT chk_feedback_rating CHECK (rating BETWEEN 1 AND 5),
          CONSTRAINT chk_feedback_category CHECK (category IN (''personal'', ''team''))
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const create = async ({ fromUserId, toUserId, teamId, content, rating }) => {
  const sql = `INSERT INTO feedbacks (fromUserId, toUserId, teamId, content, rating, category, createdAt)
               VALUES (:fromUserId, :toUserId, :teamId, :content, :rating, :category, SYSDATE)`;
  await execute(sql, {
    fromUserId,
    toUserId,
    teamId: teamId || null,
    content,
    rating,
    category: teamId ? 'team' : 'personal'
  });
  const result = await execute(
    `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
     FROM feedbacks
     WHERE fromUserId = :fromUserId AND toUserId = :toUserId AND content = :content
     ORDER BY id DESC FETCH FIRST 1 ROWS ONLY`,
    { fromUserId, toUserId, content }
  );
  return result.rows[0] || null;
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const clause = keys.length ? `WHERE ${keys.map((key) => `${key} = :${key}`).join(' AND ')}` : '';
  const sql = `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
               FROM feedbacks ${clause}
               ORDER BY createdAt DESC, id DESC`;
  const result = await execute(sql, filter);
  return result.rows;
};

const findByTeamId = async (teamId) => {
  const sql = `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
               FROM feedbacks
               WHERE teamId = :teamId
               ORDER BY createdAt DESC, id DESC`;
  const result = await execute(sql, { teamId });
  return result.rows;
};

module.exports = { ensureTable, create, find, findByTeamId };

>>>>>>> 6b0dad0c16077e3674c3d16d79957895695a9153
