const db = require('../config/db.config');

const selectFields = `
  id AS "id",
  fromUserId AS "fromUserId",
  toUserId AS "toUserId",
  teamId AS "teamId",
  content AS "content",
  rating AS "rating",
  category AS "category",
  createdAt AS "createdAt"
`;

const buildWhere = (filter = {}) => {
  const keys = Object.keys(filter).filter((key) => filter[key] !== undefined && filter[key] !== null);
  return {
    clause: keys.length ? `WHERE ${keys.map((key) => `${key} = :${key}`).join(' AND ')}` : '',
    binds: keys.reduce((binds, key) => ({ ...binds, [key]: filter[key] }), {})
  };
};

const Feedback = {
  ensureTable: async () => {
    await db.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE feedbacks (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fromUserId NUMBER NOT NULL,
            toUserId NUMBER NOT NULL,
            teamId NUMBER NULL,
            content VARCHAR2(1000 CHAR) NOT NULL,
            rating NUMBER(1) DEFAULT 5 NOT NULL,
            category VARCHAR2(20 CHAR) DEFAULT ''team'' NOT NULL,
            createdAt DATE DEFAULT SYSDATE NOT NULL
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN
            RAISE;
          END IF;
      END;
    `);
  },

  create: async ({ fromUserId, toUserId, teamId, content, rating }) => {
    await db.execute(
      `INSERT INTO feedbacks (fromUserId, toUserId, teamId, content, rating, category, createdAt)
       VALUES (:fromUserId, :toUserId, :teamId, :content, :rating, :category, SYSDATE)`,
      {
        fromUserId,
        toUserId,
        teamId: teamId || null,
        content,
        rating,
        category: teamId ? 'team' : 'personal'
      }
    );
    const result = await db.execute(
      `SELECT ${selectFields}
       FROM feedbacks
       WHERE fromUserId = :fromUserId AND toUserId = :toUserId AND content = :content
       ORDER BY id DESC
       FETCH FIRST 1 ROWS ONLY`,
      { fromUserId, toUserId, content }
    );
    return result.rows[0] || null;
  },

  find: async (filter = {}) => {
    const { clause, binds } = buildWhere(filter);
    const result = await db.execute(
      `SELECT ${selectFields} FROM feedbacks ${clause} ORDER BY createdAt DESC, id DESC`,
      binds
    );
    return result.rows;
  },

  findByTeamId: async (teamId) => Feedback.find({ teamId })
};

module.exports = Feedback;
