const { execute } = require('../config/db.config');

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE feedbacks (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          fromUserId NUMBER NOT NULL,
          toUserId NUMBER NOT NULL,
          teamId NUMBER NULL,
          content VARCHAR2(1000) NOT NULL,
          rating NUMBER(1) DEFAULT 5 NOT NULL,
          category VARCHAR2(20) DEFAULT ''team'' NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL,
          CONSTRAINT chk_feedback_rating CHECK (rating BETWEEN 1 AND 5),
          CONSTRAINT chk_feedback_category CHECK (category IN (''personal'', ''team''))
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const create = async ({ fromUserId, toUserId, teamId, content, rating }) => {
  const sql = `INSERT INTO feedbacks (fromUserId, toUserId, teamId, content, rating, category, createdAt)
               VALUES (:fromUserId, :toUserId, :teamId, :content, :rating, :category, SYSDATE)`;
  await execute(sql, {
    fromUserId,
    toUserId,
    teamId: teamId || null,
    content,
    rating,
    category: teamId ? 'team' : 'personal'
  });
  const result = await execute(
    `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
     FROM feedbacks
     WHERE fromUserId = :fromUserId AND toUserId = :toUserId AND content = :content
     ORDER BY id DESC FETCH FIRST 1 ROWS ONLY`,
    { fromUserId, toUserId, content }
  );
  return result.rows[0] || null;
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const clause = keys.length ? `WHERE ${keys.map((key) => `${key} = :${key}`).join(' AND ')}` : '';
  const sql = `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
               FROM feedbacks ${clause}
               ORDER BY createdAt DESC, id DESC`;
  const result = await execute(sql, filter);
  return result.rows;
};

const findByTeamId = async (teamId) => {
  const sql = `SELECT id AS "id", fromUserId AS "fromUserId", toUserId AS "toUserId", teamId AS "teamId", content AS "content", rating AS "rating", category AS "category", createdAt AS "createdAt"
               FROM feedbacks
               WHERE teamId = :teamId
               ORDER BY createdAt DESC, id DESC`;
  const result = await execute(sql, { teamId });
  return result.rows;
};

module.exports = { ensureTable, create, find, findByTeamId };
