<<<<<<< HEAD
const db = require('../config/db.config');

const Friend = {
  createRequest: async ({ requesterId, addresseeId }) => {
    const query = `
      INSERT INTO friends (requesterId, addresseeId, status)
      VALUES (?, ?, 'PENDING')
    `;
    const [result] = await db.execute(query, [requesterId, addresseeId]);
    return result;
  },

  findRelationshipBetweenUsers: async (userId, otherUserId) => {
    const query = `
      SELECT id, requesterId, addresseeId, status, createdAt, acceptedAt
      FROM friends
      WHERE (requesterId = ? AND addresseeId = ?)
         OR (requesterId = ? AND addresseeId = ?)
      LIMIT 1
    `;
    const [rows] = await db.execute(query, [userId, otherUserId, otherUserId, userId]);
    return rows[0] || null;
  },

  findIncomingRequests: async (userId) => {
    const query = `
      SELECT f.id, f.requesterId, f.addresseeId, f.status, f.createdAt,
             u.name AS requesterName, u.email AS requesterEmail
      FROM friends f
      JOIN users u ON u.id = f.requesterId
      WHERE f.addresseeId = ? AND f.status = 'PENDING'
      ORDER BY f.createdAt DESC
    `;
    const [rows] = await db.execute(query, [userId]);
    return rows;
  },

  acceptRequest: async ({ requestId, userId }) => {
    const query = `
      UPDATE friends
      SET status = 'ACCEPTED', acceptedAt = NOW()
      WHERE id = ? AND addresseeId = ? AND status = 'PENDING'
    `;
    const [result] = await db.execute(query, [requestId, userId]);
    return result;
  },

  deleteRelationship: async ({ userId, friendId }) => {
    const query = `
      DELETE FROM friends
      WHERE (requesterId = ? AND addresseeId = ?)
         OR (requesterId = ? AND addresseeId = ?)
    `;
    const [result] = await db.execute(query, [userId, friendId, friendId, userId]);
    return result;
  },

  findAcceptedFriends: async (userId) => {
    const query = `
      SELECT
        CASE
          WHEN requesterId = ? THEN addresseeId
          ELSE requesterId
        END AS friendId
      FROM friends
      WHERE status = 'ACCEPTED'
        AND (requesterId = ? OR addresseeId = ?)
    `;
    const [rows] = await db.execute(query, [userId, userId, userId]);
    return rows.map((row) => row.friendId);
  }
};

module.exports = Friend;
=======
const { execute } = require('../config/db.config');

const ensureTable = async () => {
  try {
    await execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE friends (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            userId NUMBER NOT NULL,
            friendId NUMBER NOT NULL,
            status VARCHAR2(20) DEFAULT ''pending'' NOT NULL,
            createdAt DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT chk_friends_status CHECK (status IN (''pending'', ''accepted'')),
            CONSTRAINT uq_friends_pair UNIQUE (userId, friendId)
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN
            RAISE;
          END IF;
      END;
    `);
  } catch (error) {
    console.error('Failed to ensure friends table:', error);
    throw error;
  }
};

const create = async ({ userId, friendId }) => {
  const sql = `INSERT INTO friends (userId, friendId, status, createdAt) VALUES (:userId, :friendId, 'pending', SYSDATE)`;
  await execute(sql, { userId, friendId });
  const rows = await find({ userId, friendId });
  return rows[0] || null;
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const clause = keys.length ? `WHERE ${keys.map((key) => `${key} = :${key}`).join(' AND ')}` : '';
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt" FROM friends ${clause}`;
  const result = await execute(sql, filter);
  return result.rows;
};

const findPair = async (userId, friendId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE (userId = :userId AND friendId = :friendId)
                  OR (userId = :friendId AND friendId = :userId)`;
  const result = await execute(sql, { userId, friendId });
  return result.rows[0] || null;
};

const findIncomingPending = async (friendId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE friendId = :friendId AND status = 'pending'
               ORDER BY createdAt DESC`;
  const result = await execute(sql, { friendId });
  return result.rows;
};

const findAcceptedByUser = async (userId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE (userId = :userId OR friendId = :userId) AND status = 'accepted'
               ORDER BY createdAt DESC`;
  const result = await execute(sql, { userId });
  return result.rows;
};

const updateStatus = async (id, status) => {
  await execute(`UPDATE friends SET status = :status WHERE id = :id`, { id, status });
  const rows = await find({ id });
  return rows[0] || null;
};

const deleteById = async (id) => {
  await execute(`DELETE FROM friends WHERE id = :id`, { id });
};

module.exports = { ensureTable, create, find, findPair, findIncomingPending, findAcceptedByUser, updateStatus, deleteById };
>>>>>>> 6b0dad0c16077e3674c3d16d79957895695a9153
