const { execute } = require('../config/db.config');

const ensureTable = async () => {
  try {
    await execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE friends (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            userId NUMBER NOT NULL,
            friendId NUMBER NOT NULL,
            status VARCHAR2(20) DEFAULT ''pending'' NOT NULL,
            createdAt DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT chk_friends_status CHECK (status IN (''pending'', ''accepted'')),
            CONSTRAINT uq_friends_pair UNIQUE (userId, friendId)
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN
            RAISE;
          END IF;
      END;
    `);
  } catch (error) {
    console.error('Failed to ensure friends table:', error);
    throw error;
  }
};

const create = async ({ userId, friendId }) => {
  const sql = `INSERT INTO friends (userId, friendId, status, createdAt) VALUES (:userId, :friendId, 'pending', SYSDATE)`;
  await execute(sql, { userId, friendId });
  const rows = await find({ userId, friendId });
  return rows[0] || null;
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const clause = keys.length ? `WHERE ${keys.map((key) => `${key} = :${key}`).join(' AND ')}` : '';
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt" FROM friends ${clause}`;
  const result = await execute(sql, filter);
  return result.rows;
};

const findPair = async (userId, friendId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE (userId = :userId AND friendId = :friendId)
                  OR (userId = :friendId AND friendId = :userId)`;
  const result = await execute(sql, { userId, friendId });
  return result.rows[0] || null;
};

const findIncomingPending = async (friendId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE friendId = :friendId AND status = 'pending'
               ORDER BY createdAt DESC`;
  const result = await execute(sql, { friendId });
  return result.rows;
};

const findAcceptedByUser = async (userId) => {
  const sql = `SELECT id AS "id", userId AS "userId", friendId AS "friendId", status AS "status", createdAt AS "createdAt"
               FROM friends
               WHERE (userId = :userId OR friendId = :userId) AND status = 'accepted'
               ORDER BY createdAt DESC`;
  const result = await execute(sql, { userId });
  return result.rows;
};

const updateStatus = async (id, status) => {
  await execute(`UPDATE friends SET status = :status WHERE id = :id`, { id, status });
  const rows = await find({ id });
  return rows[0] || null;
};

const deleteById = async (id) => {
  await execute(`DELETE FROM friends WHERE id = :id`, { id });
};

module.exports = { ensureTable, create, find, findPair, findIncomingPending, findAcceptedByUser, updateStatus, deleteById };
