const { execute } = require('../config/db.config');

const rowSelect = `
  id AS "id",
  userId AS "userId",
  type AS "type",
  message AS "message",
  targetType AS "targetType",
  targetId AS "targetId",
  actionPath AS "actionPath",
  dedupeKey AS "dedupeKey",
  isRead AS "isRead",
  createdAt AS "createdAt"
`;

const runIgnore = async (sql, ignoredCodes = []) => {
  try {
    await execute(sql);
  } catch (error) {
    if (!ignoredCodes.includes(error.errorNum)) throw error;
  }
};

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE notifications (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          userId NUMBER NOT NULL,
          type VARCHAR2(50 CHAR) NOT NULL,
          message VARCHAR2(500 CHAR) NOT NULL,
          targetType VARCHAR2(50 CHAR),
          targetId VARCHAR2(100 CHAR),
          actionPath VARCHAR2(200 CHAR),
          dedupeKey VARCHAR2(200 CHAR),
          isRead NUMBER(1) DEFAULT 0 NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await runIgnore(`ALTER TABLE notifications ADD targetType VARCHAR2(50 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE notifications ADD targetId VARCHAR2(100 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE notifications ADD actionPath VARCHAR2(200 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE notifications ADD dedupeKey VARCHAR2(200 CHAR)`, [1430]);
};

const create = async ({ userId, type, message, targetType = null, targetId = null, actionPath = null, dedupeKey = null }) => {
  await execute(
    `INSERT INTO notifications (userId, type, message, targetType, targetId, actionPath, dedupeKey, isRead, createdAt)
     VALUES (:userId, :type, :message, :targetType, :targetId, :actionPath, :dedupeKey, 0, SYSDATE)`,
    { userId, type, message, targetType, targetId, actionPath, dedupeKey }
  );

  const result = await execute(
    `SELECT ${rowSelect}
     FROM notifications
     WHERE userId = :userId
     ORDER BY createdAt DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { userId }
  );
  return result.rows[0] || null;
};

const createOnce = async ({ userId, type, message, targetType = null, targetId = null, actionPath = null, dedupeKey }) => {
  if (!dedupeKey) {
    return create({ userId, type, message, targetType, targetId, actionPath });
  }

  const existing = await find({ userId, dedupeKey });
  if (existing.length) return existing[0];

  return create({ userId, type, message, targetType, targetId, actionPath, dedupeKey });
};

const find = async (filter) => {
  const keys = Object.keys(filter || {});
  const columnMap = {
    id: 'id',
    userId: 'userId',
    type: 'type',
    targetType: 'targetType',
    targetId: 'targetId',
    dedupeKey: 'dedupeKey',
    isRead: 'isRead'
  };
  const validKeys = keys.filter((key) => columnMap[key]);
  const clause = validKeys.length ? `WHERE ${validKeys.map((key) => `${columnMap[key]} = :${key}`).join(' AND ')}` : '';
  const binds = validKeys.reduce((acc, key) => ({ ...acc, [key]: filter[key] }), {});
  const sql = `SELECT ${rowSelect} FROM notifications ${clause} ORDER BY createdAt DESC, id DESC`;
  const result = await execute(sql, binds);
  return result.rows;
};

const findByIdAndUpdate = async (id, updates) => {
  const fields = Object.keys(updates);
  if (!fields.length) return null;
  const normalizedUpdates = { ...updates };
  if (Object.prototype.hasOwnProperty.call(normalizedUpdates, 'isRead')) {
    normalizedUpdates.isRead = normalizedUpdates.isRead ? 1 : 0;
  }
  const setClauses = fields.map((field) => `${field} = :${field}`);
  const binds = { id, ...normalizedUpdates };
  const sql = `UPDATE notifications SET ${setClauses.join(', ')} WHERE id = :id`;
  await execute(sql, binds);
  const result = await execute(`SELECT ${rowSelect} FROM notifications WHERE id = :id`, { id });
  return result.rows[0] || null;
};

const deleteById = async (id) => {
  await execute(`DELETE FROM notifications WHERE id = :id`, { id });
};

module.exports = { ensureTable, create, createOnce, find, findByIdAndUpdate, deleteById };

