const { execute } = require('../config/db.config');

const runIgnore = async (sql, ignoredCodes = []) => {
  try {
    await execute(sql);
  } catch (error) {
    if (!ignoredCodes.includes(error.errorNum)) throw error;
  }
};

const rowSelect = `
  id AS "id",
  userId AS "userId",
  teamId AS "teamId",
  type AS "type",
  title AS "title",
  DBMS_LOB.SUBSTR(description, 2000, 1) AS "description",
  dpName AS "dpName",
  status AS "status",
  targetDate AS "targetDate",
  createdAt AS "createdAt",
  updatedAt AS "updatedAt"
`;

const ensureTable = async () => {
  await execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE tasks_schedules (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          userId NUMBER,
          teamId NUMBER,
          type VARCHAR2(30 CHAR) DEFAULT ''Task'' NOT NULL,
          title VARCHAR2(200 CHAR) NOT NULL,
          description VARCHAR2(2000 CHAR),
          dpName VARCHAR2(200 CHAR),
          status VARCHAR2(30 CHAR) DEFAULT ''Wait'' NOT NULL,
          targetDate DATE NOT NULL,
          createdAt DATE DEFAULT SYSDATE NOT NULL,
          updatedAt DATE DEFAULT SYSDATE NOT NULL
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);

  await runIgnore(`ALTER TABLE tasks_schedules ADD userId NUMBER`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD teamId NUMBER`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD type VARCHAR2(30 CHAR) DEFAULT 'Task' NOT NULL`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules MODIFY type VARCHAR2(30 CHAR)`, []);
  await runIgnore(`ALTER TABLE tasks_schedules DROP CONSTRAINT SYS_C008357`, [2443]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD title VARCHAR2(200 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD description VARCHAR2(2000 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD dpName VARCHAR2(200 CHAR)`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD status VARCHAR2(30 CHAR) DEFAULT 'Wait' NOT NULL`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD targetDate DATE`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD createdAt DATE DEFAULT SYSDATE NOT NULL`, [1430]);
  await runIgnore(`ALTER TABLE tasks_schedules ADD updatedAt DATE DEFAULT SYSDATE NOT NULL`, [1430]);
};

const findById = async (id) => {
  const result = await execute(
    `SELECT ${rowSelect} FROM tasks_schedules WHERE id = :id`,
    { id }
  );
  return result.rows[0] || null;
};

const create = async ({ userId, teamId = null, type, title, description, dpName, targetDate }) => {
  await execute(
    `INSERT INTO tasks_schedules (userId, teamId, type, title, description, dpName, status, targetDate, createdAt, updatedAt)
     VALUES (:userId, :teamId, :type, :title, :description, :dpName, 'Wait', TO_DATE(:targetDate, 'YYYY-MM-DD'), SYSDATE, SYSDATE)`,
    { userId, teamId, type, title, description, dpName, targetDate }
  );

  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE userId = :userId
       AND title = :title
       AND targetDate = TO_DATE(:targetDate, 'YYYY-MM-DD')
     ORDER BY createdAt DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { userId, title, targetDate }
  );
  return result.rows[0] || null;
};

const findAll = async (userId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE userId = :userId
     ORDER BY targetDate ASC, id DESC`,
    { userId }
  );
  return result.rows;
};

const findByTeamId = async (teamId, userId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE teamId = :teamId AND (userId = :userId OR userId IS NULL)
     ORDER BY targetDate ASC, id DESC`,
    { teamId, userId }
  );
  return result.rows;
};

const getTeamProgressStats = async (teamId) => {
  const result = await execute(
    `SELECT
       COUNT(*) AS "total",
       SUM(CASE WHEN status = 'Done' THEN 1 ELSE 0 END) AS "done"
     FROM tasks_schedules
     WHERE teamId = :teamId AND type = 'ProjectTodo'`,
    { teamId }
  );
  const row = result.rows[0] || {};
  const total = Number(row.total) || 0;
  const done = Number(row.done) || 0;
  const progress = total > 0 ? Math.round((done / total) * 100) : 0;
  return { total, done, progress };
};

const findProjectTodosByTeamId = async (teamId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE teamId = :teamId AND type = 'ProjectTodo'
     ORDER BY createdAt ASC, id ASC`,
    { teamId }
  );
  return result.rows;
};

const updateProjectTodoStatus = async (todoId, teamId, status) => {
  await execute(
    `UPDATE tasks_schedules SET status = :status, updatedAt = SYSDATE
     WHERE id = :id AND teamId = :teamId AND type = 'ProjectTodo'`,
    { status, id: todoId, teamId }
  );
  return findById(todoId);
};

const deleteProjectTodoById = async (todoId, teamId) => {
  await execute(
    `DELETE FROM tasks_schedules
     WHERE id = :id AND teamId = :teamId AND type = 'ProjectTodo'`,
    { id: todoId, teamId }
  );
};

const findByIdAndUpdate = async (id, userId, updates) => {
  const fields = Object.keys(updates || {});
  if (!fields.length) return findById(id);

  const setClauses = fields.map((field) => {
    if (field === 'targetDate') return `${field} = TO_DATE(:${field}, 'YYYY-MM-DD')`;
    return `${field} = :${field}`;
  });

  const result = await execute(
    `UPDATE tasks_schedules
     SET ${setClauses.join(', ')}, updatedAt = SYSDATE
     WHERE id = :id AND (userId = :userId OR userId IS NULL)`,
    { id, userId, ...updates }
  );
  if (!result.rowsAffected) return null;
  return findById(id);
};

const deleteById = async (id, userId) => {
  await execute(
    `DELETE FROM tasks_schedules
     WHERE id = :id AND (userId = :userId OR userId IS NULL)`,
    { id, userId }
  );
};

module.exports = { ensureTable, create, findAll, findByTeamId, getTeamProgressStats, findProjectTodosByTeamId, updateProjectTodoStatus, deleteProjectTodoById, findByIdAndUpdate, deleteById };
