const { execute } = require('../config/db.config');

const normalizeTeamId = (teamId) => {
  return teamId === '' || teamId === undefined || teamId === null ? null : teamId;
};

const ignoreSchemaError = (error) => {
  const message = String(error?.message || '');
  return message.includes('ORA-00955') || message.includes('ORA-01430');
};

const runSchemaSql = async (sql) => {
  try {
    await execute(sql);
  } catch (error) {
    if (!ignoreSchemaError(error)) throw error;
  }
};

const ensureColumn = async (columnName, definition) => {
  const result = await execute(
    `SELECT 1
     FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TASKS_SCHEDULES'
       AND COLUMN_NAME = :columnName`,
    { columnName }
  );

  if (result.rows.length === 0) {
    await execute(`ALTER TABLE tasks_schedules ADD (${definition})`);
  }
};

const ensureTable = async () => {
  await runSchemaSql(`
    CREATE TABLE tasks_schedules (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      userId NUMBER NOT NULL,
      teamId NUMBER NULL,
      type VARCHAR2(50 CHAR) DEFAULT 'Task' NOT NULL,
      title VARCHAR2(200 CHAR) NOT NULL,
      description CLOB,
      dpName CLOB,
      status VARCHAR2(30 CHAR) DEFAULT 'Wait' NOT NULL,
      targetDate DATE NOT NULL,
      createdAt DATE DEFAULT SYSDATE NOT NULL,
      updatedAt DATE DEFAULT SYSDATE NOT NULL
    )
  `);

  await ensureColumn('USERID', 'userId NUMBER');
  await ensureColumn('TEAMID', 'teamId NUMBER');
  await ensureColumn('TYPE', `type VARCHAR2(50 CHAR) DEFAULT 'Task'`);
  await ensureColumn('TITLE', 'title VARCHAR2(200 CHAR)');
  await ensureColumn('DESCRIPTION', 'description CLOB');
  await ensureColumn('DPNAME', 'dpName CLOB');
  await ensureColumn('STATUS', `status VARCHAR2(30 CHAR) DEFAULT 'Wait'`);
  await ensureColumn('TARGETDATE', 'targetDate DATE');
  await ensureColumn('CREATEDAT', 'createdAt DATE DEFAULT SYSDATE');
  await ensureColumn('UPDATEDAT', 'updatedAt DATE DEFAULT SYSDATE');
};

const rowSelect = `
  id AS "id",
  userId AS "userId",
  teamId AS "teamId",
  type AS "type",
  title AS "title",
  DBMS_LOB.SUBSTR(description, 4000, 1) AS "description",
  dpName AS "dpName",
  status AS "status",
  targetDate AS "targetDate",
  createdAt AS "createdAt",
  updatedAt AS "updatedAt"
`;

const create = async ({ userId, teamId = null, type, title, description, dpName, targetDate }) => {
  const normalizedTeamId = normalizeTeamId(teamId);

  await execute(
    `INSERT INTO tasks_schedules (userId, teamId, type, title, description, dpName, status, targetDate, createdAt, updatedAt)
     VALUES (:userId, :teamId, :type, :title, :description, :dpName, 'Wait', TO_DATE(:targetDate, 'YYYY-MM-DD'), SYSDATE, SYSDATE)`,
    { userId, teamId: normalizedTeamId, type, title, description, dpName, targetDate }
  );

  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE userId = :userId
       AND NVL(teamId, -1) = NVL(:teamId, -1)
       AND title = :title
       AND targetDate = TO_DATE(:targetDate, 'YYYY-MM-DD')
     ORDER BY createdAt DESC, id DESC
     FETCH FIRST 1 ROWS ONLY`,
    { userId, teamId: normalizedTeamId, title, targetDate }
  );
  return result.rows[0] || null;
};

const findAll = async (userId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE userId = :userId OR teamId IN (
       SELECT teamid FROM team_members WHERE userid = (
         SELECT userid FROM users WHERE id = :userId
       )
     )
     ORDER BY targetDate, id`,
    { userId }
  );
  return result.rows;
};

const findByTeamId = async (teamId, userId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE teamId = :teamId
       AND (userId = :userId OR :userId IS NOT NULL)
     ORDER BY targetDate, id`,
    { teamId, userId }
  );
  return result.rows;
};

const getTeamProgressStats = async (teamId) => {
  const result = await execute(
    `SELECT COUNT(*) AS "total",
            SUM(CASE WHEN status = 'Done' THEN 1 ELSE 0 END) AS "done"
     FROM tasks_schedules
     WHERE teamId = :teamId
       AND type = 'ProjectTodo'`,
    { teamId }
  );

  const row = result.rows[0] || {};
  const total = Number(row.total || 0);
  const done = Number(row.done || 0);
  return {
    total,
    done,
    progress: total > 0 ? Math.round((done / total) * 100) : 0
  };
};

const findProjectTodosByTeamId = async (teamId) => {
  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE teamId = :teamId
       AND type = 'ProjectTodo'
     ORDER BY targetDate, id`,
    { teamId }
  );
  return result.rows;
};

const updateProjectTodoStatus = async (id, teamId, status) => {
  await execute(
    `UPDATE tasks_schedules
     SET status = :status,
         updatedAt = SYSDATE
     WHERE id = :id
       AND teamId = :teamId
       AND type = 'ProjectTodo'`,
    { id, teamId, status }
  );

  const result = await execute(
    `SELECT ${rowSelect}
     FROM tasks_schedules
     WHERE id = :id
       AND teamId = :teamId
       AND type = 'ProjectTodo'`,
    { id, teamId }
  );
  return result.rows[0] || null;
};

const deleteProjectTodoById = async (id, teamId) => {
  await execute(
    `DELETE FROM tasks_schedules
     WHERE id = :id
       AND teamId = :teamId
       AND type = 'ProjectTodo'`,
    { id, teamId }
  );
};

const findByIdAndUpdate = async (id, userId, updates) => {
  const fields = Object.keys(updates || {});
  if (!fields.length) return null;

  const binds = { id, userId };
  const setClauses = fields.map((field) => {
    const bindName = `update_${field}`;
    binds[bindName] = updates[field];
    return field === 'targetDate'
      ? `targetDate = TO_DATE(:${bindName}, 'YYYY-MM-DD')`
      : `${field} = :${bindName}`;
  });
  setClauses.push('updatedAt = SYSDATE');

  await execute(
    `UPDATE tasks_schedules SET ${setClauses.join(', ')} WHERE id = :id AND userId = :userId`,
    binds
  );
  const result = await execute(
    `SELECT ${rowSelect} FROM tasks_schedules WHERE id = :id AND userId = :userId`,
    { id, userId }
  );
  return result.rows[0] || null;
};

const deleteById = async (id, userId) => {
  await execute(`DELETE FROM tasks_schedules WHERE id = :id AND userId = :userId`, { id, userId });
};

module.exports = {
  ensureTable,
  create,
  findAll,
  findByTeamId,
  getTeamProgressStats,
  findProjectTodosByTeamId,
  updateProjectTodoStatus,
  deleteProjectTodoById,
  findByIdAndUpdate,
  deleteById
};
